data:
  train_url: "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
  column_names:
    - "age"
    - "workclass"
    - "fnlwgt"
    - "education"
    - "education-num"
    - "marital-status"
    - "occupation"
    - "relationship"
    - "race"
    - "sex"
    - "capital-gain"
    - "capital-loss"
    - "hours-per-week"
    - "native-country"
    - "income"

# MLOps Configs: Thresholds for alerts
validation:
  drift_threshold: 0.01  # Jensen-Shannon divergence limit
  min_domain_mass: 0.9   # % of values that must be in the known domain
  environment: "SERVING" # Default environment for checks